/// Localized copy for monthly analysis PDF reports.
abstract final class PDFContent {
  PDFContent._();

  static Map<String, String> labels(String lang) => {
        'reportTitle': lang == 'ar' ? 'تقرير مالي شهري' : 'Monthly Financial Report',
        'generatedBy': lang == 'ar'
            ? 'تم إنشاؤه بواسطة تطبيق مدبّر'
            : 'Generated by Mudabbir app',
        'totalBalance': lang == 'ar' ? 'إجمالي الرصيد' : 'Total Balance',
        'totalIncome': lang == 'ar' ? 'إجمالي الدخل' : 'Total Income',
        'totalExpenses': lang == 'ar' ? 'إجمالي المصروفات' : 'Total Expenses',
        'netSavings': lang == 'ar' ? 'صافي التوفير' : 'Net Savings',
        'healthScore': lang == 'ar' ? 'درجة الصحة المالية' : 'Financial Health Score',
        'savingsRate': lang == 'ar' ? 'معدل الادخار' : 'Savings Rate',
        'expenseBreakdown':
            lang == 'ar' ? 'توزيع المصروفات' : 'Expense Breakdown',
        'aiRecommendation': lang == 'ar'
            ? 'توصية مدبّر الذكية'
            : 'Mudabbir\'s Smart Recommendation',
        'forecast': lang == 'ar' ? 'توقعات الشهر القادم' : 'Next Month Forecast',
        'behavior':
            lang == 'ar' ? 'تحليل السلوك المالي' : 'Financial Behavior Analysis',
      };

  static String recommendation({
    required double savingsRate,
    required String topCategory,
    required int pct,
    required String lang,
  }) {
    if (lang == 'ar') {
      if (savingsRate < 10) {
        return 'معدل ادخارك ${savingsRate.toStringAsFixed(1)}% — حاول تخفيض مصاريف $topCategory للوصول لـ 20% على الأقل.';
      } else if (savingsRate < 20) {
        return 'أنت على المسار الصحيح! خفّض إنفاقك على $topCategory ($pct% من مصاريفك) قليلاً وراح تصل لمعدل ادخار ممتاز.';
      }
      return 'معدل ادخارك ممتاز! استمر بنفس النهج وفكّر في وضع أهداف ادخار طموحة للشهر القادم.';
    }
    if (savingsRate < 10) {
      return 'Your savings rate is ${savingsRate.toStringAsFixed(1)}% — try reducing $topCategory spending to reach at least 20%.';
    } else if (savingsRate < 20) {
      return 'You\'re on the right track! Trim your $topCategory spending ($pct% of expenses) a bit and you\'ll hit an excellent savings rate.';
    }
    return 'Excellent savings rate! Keep it up and consider setting more ambitious savings goals for next month.';
  }
}
