import 'dart:io';

import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:share_plus/share_plus.dart';

class FinancialReportService {
  Future<void> shareMonthlyReport({
    required double income,
    required double expense,
    required double balance,
    required int healthScore,
    required List<String> alerts,
    required Map<String, double> categoryBreakdown,
  }) async {
    final pdf = pw.Document();
    final now = DateTime.now();
    final monthLabel = '${now.year}-${now.month.toString().padLeft(2, '0')}';

    pdf.addPage(
      pw.Page(
        build: (context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                'Mudabbir Monthly Financial Report',
                style: pw.TextStyle(
                  fontSize: 22,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.SizedBox(height: 8),
              pw.Text('Period: $monthLabel'),
              pw.SizedBox(height: 24),
              pw.Text(
                'Executive Summary',
                style: pw.TextStyle(
                  fontSize: 16,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.SizedBox(height: 8),
              pw.Bullet(text: 'Total income: ${income.toStringAsFixed(2)} SAR'),
              pw.Bullet(
                text: 'Total expense: ${expense.toStringAsFixed(2)} SAR',
              ),
              pw.Bullet(text: 'Net balance: ${balance.toStringAsFixed(2)} SAR'),
              pw.Bullet(text: 'Financial health score: $healthScore/100'),
              pw.SizedBox(height: 16),
              pw.Text(
                'Expense Breakdown (Visual)',
                style: pw.TextStyle(
                  fontSize: 16,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.SizedBox(height: 8),
              if (categoryBreakdown.isEmpty)
                pw.Text('No category expense data for this period.')
              else
                ..._buildCategoryBars(categoryBreakdown),
              pw.SizedBox(height: 16),
              pw.Text(
                'Alerts',
                style: pw.TextStyle(
                  fontSize: 16,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.SizedBox(height: 8),
              if (alerts.isEmpty)
                pw.Text('No abnormal spending alerts for this period.')
              else
                ...alerts.map((a) => pw.Bullet(text: a)),
              pw.Spacer(),
              pw.Text(
                'Generated by Mudabbir',
                style: const pw.TextStyle(fontSize: 10),
              ),
            ],
          );
        },
      ),
    );

    final dir = await getTemporaryDirectory();
    final file = File('${dir.path}/mudabbir-report-$monthLabel.pdf');
    await file.writeAsBytes(await pdf.save());

    await Share.shareXFiles(
      [XFile(file.path)],
      text: 'Monthly financial report - Mudabbir',
      subject: 'Mudabbir Financial Report ($monthLabel)',
    );
  }

  List<pw.Widget> _buildCategoryBars(Map<String, double> categoryBreakdown) {
    final total = categoryBreakdown.values.fold<double>(0, (a, b) => a + b);
    if (total <= 0) {
      return [pw.Text('No expense totals found.')];
    }

    final sorted = categoryBreakdown.entries.toList()
      ..sort((a, b) => b.value.compareTo(a.value));
    final top = sorted.take(6).toList();

    return top.map((entry) {
      final ratio = (entry.value / total).clamp(0.0, 1.0).toDouble();
      final percent = (ratio * 100).toStringAsFixed(0);
      return pw.Padding(
        padding: const pw.EdgeInsets.only(bottom: 8),
        child: pw.Column(
          crossAxisAlignment: pw.CrossAxisAlignment.start,
          children: [
            pw.Text(
              '${entry.key}: ${entry.value.toStringAsFixed(0)} SAR ($percent%)',
              style: const pw.TextStyle(fontSize: 10),
            ),
            pw.SizedBox(height: 3),
            pw.Container(
              height: 8,
              width: 260,
              decoration: pw.BoxDecoration(
                borderRadius: pw.BorderRadius.circular(4),
                color: PdfColor.fromHex('#E5E7EB'),
              ),
              child: pw.Align(
                alignment: pw.Alignment.centerLeft,
                child: pw.Container(
                  height: 8,
                  width: 260 * ratio,
                  decoration: pw.BoxDecoration(
                    borderRadius: pw.BorderRadius.circular(4),
                    color: PdfColor.fromHex('#5F7F6F'),
                  ),
                ),
              ),
            ),
          ],
        ),
      );
    }).toList();
  }
}
