import 'package:intl/intl.dart';
import 'package:mudabbir/presentation/resources/chatbot_ui_strings.dart';
import 'package:mudabbir/presentation/resources/currency_formatter.dart';
import 'package:mudabbir/presentation/resources/strings_manager.dart';

/// Bilingual copy for PDF layout (matches app locale).
class FinancialReportStrings {
  FinancialReportStrings._();

  static bool get _e => AppStrings.isEnglishLocale;

  static String get appName => _e ? 'Mudabbir' : 'مدبر';

  static String get reportTitle =>
      _e ? 'Monthly Financial Report' : 'التقرير المالي الشهري';

  static String get generatedOn => _e ? 'Generated on' : 'تاريخ الإصدار';

  static String get periodLabel => _e ? 'Period' : 'الفترة';

  static String get preparedFor => _e ? 'Prepared for' : 'إعدادًا لـ';

  static String get executiveSummary =>
      _e ? 'Executive summary' : 'ملخص تنفيذي';

  static String get income => _e ? 'Income' : 'الدخل';

  static String get expense => _e ? 'Expenses' : 'المصروفات';

  static String get balance => _e ? 'Net balance' : 'صافي الرصيد';

  static String get healthScore => _e ? 'Health score' : 'درجة الصحة المالية';

  static String get savingsRate => _e ? 'Savings rate' : 'معدل الادخار';

  static String get accountBalance =>
      _e ? 'Total account balance' : 'إجمالي رصيد الحسابات';

  static String healthStatus(int score) => ChatbotUi.insightStatus(score);

  static String get categoryBreakdown =>
      _e ? 'Expense by category' : 'المصروفات حسب الفئة';

  static String get noCategoryData => _e
      ? 'No expense categories recorded this month.'
      : 'لا توجد مصروفات مصنّفة لهذا الشهر.';

  static String get goalsSection => _e ? 'Savings goals' : 'أهداف الادخار';

  static String get noGoals =>
      _e ? 'No active goals yet.' : 'لا توجد أهداف نشطة حاليًا.';

  static String get goalName => _e ? 'Goal' : 'الهدف';

  static String get goalTarget => _e ? 'Target' : 'المستهدف';

  static String get goalCurrent => _e ? 'Saved' : 'المُدخر';

  static String get goalProgress => _e ? 'Progress' : 'التقدم';

  static String get goalDeadline => _e ? 'Deadline' : 'الموعد';

  static String get budgetSection => _e ? 'Monthly budget' : 'الميزانية الشهرية';

  static String get budgetLimit => _e ? 'Budget limit' : 'حد الميزانية';

  static String get budgetSpent => _e ? 'Spent' : 'المُنفق';

  static String get budgetRemaining => _e ? 'Remaining' : 'المتبقي';

  static String get noBudget =>
      _e ? 'No budget set for this month.' : 'لم تُحدَّد ميزانية لهذا الشهر.';

  static String get transactionsSection =>
      _e ? 'Recent transactions' : 'أحدث المعاملات';

  static String get noTransactions => _e
      ? 'No transactions recorded this month.'
      : 'لا توجد معاملات مسجّلة لهذا الشهر.';

  static String get colDate => _e ? 'Date' : 'التاريخ';

  static String get colCategory => _e ? 'Category' : 'الفئة';

  static String get colType => _e ? 'Type' : 'النوع';

  static String get colAmount => _e ? 'Amount' : 'المبلغ';

  static String get colNotes => _e ? 'Notes' : 'ملاحظات';

  static String get typeIncome => _e ? 'Income' : 'دخل';

  static String get typeExpense => _e ? 'Expense' : 'مصروف';

  static String get subscriptionsSection =>
      _e ? 'Recurring expenses' : 'المصروفات المتكررة';

  static String get noSubscriptions => _e
      ? 'No recurring patterns detected.'
      : 'لم يُكتشف نمط إنفاق متكرر.';

  static String get alertsSection => _e ? 'Alerts & insights' : 'التنبيهات والملاحظات';

  static String get noAlerts => ChatbotUi.noSpendingAlerts;

  static String get recommendationsSection =>
      _e ? 'Recommendations' : 'توصيات';

  static String recommendations(int score) {
    if (_e) {
      if (score >= 75) {
        return 'Keep your current savings habit. Review goals monthly and redirect surplus to your nearest deadline.';
      }
      if (score >= 50) {
        return 'Track top spending categories weekly. Try allocating a fixed amount to savings right after income.';
      }
      return 'Prioritize reducing non-essential spending. Set a monthly budget and monitor alerts in the app.';
    }
    if (score >= 75) {
      return 'حافظ على وتيرة ادخارك الحالية. راجع أهدافك شهريًا ووجّه الفائض نحو أقرب موعد.';
    }
    if (score >= 50) {
      return 'تابع أكبر فئات الإنفاق أسبوعيًا. خصّص مبلغًا ثابتًا للادخار مباشرة بعد استلام الدخل.';
    }
    return 'ركّز على تقليل الإنفاق غير الضروري. حدّد ميزانية شهرية وراقب التنبيهات داخل التطبيق.';
  }

  static String get footer =>
      _e ? 'Generated by Mudabbir · Personal finance assistant' : 'صُنع بواسطة مدبر · مساعدك المالي الشخصي';

  static String get shareSubject => _e
      ? 'Mudabbir monthly financial report'
      : 'التقرير المالي الشهري — مدبر';

  static String shareBody(String period) => _e
      ? 'Your Mudabbir financial report for $period'
      : 'تقريرك المالي من مدبر للفترة $period';

  static String get otherCategory => _e ? 'Other' : 'أخرى';

  static String formatAmount(double value) => AppCurrency.format(value);

  static String formatPercent(double value) =>
      '${value.toStringAsFixed(0)}%';

  static String formatPeriod(DateTime period) {
    if (_e) {
      return DateFormat('MMMM yyyy', 'en').format(period);
    }
    return DateFormat('MMMM yyyy', 'ar').format(period);
  }

  static String formatDate(DateTime date) {
    if (_e) {
      return DateFormat('d MMM yyyy', 'en').format(date);
    }
    return DateFormat('d MMM yyyy', 'ar').format(date);
  }

  static String formatShortDate(String iso) {
    final parsed = DateTime.tryParse(iso);
    if (parsed == null) return iso;
    if (_e) {
      return DateFormat('d/M').format(parsed);
    }
    return DateFormat('d/M', 'ar').format(parsed);
  }
}
